local_enable=YES
write_enable=NO 

chroot_local_user=YES
allow_writeable_chroot=NO

pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=185.100.234.107

anonymous_enable=NO
xferlog_enable=YES
log_ftp_protocol=YES
foreground=YES