// <auto-generated />
using System;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.Indices
{
    [DbContext(typeof(MasofaIndicesDbContext))]
    [Migration("20251125075232_PreviewPath_Added")]
    partial class PreviewPath_Added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.ArviPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("BZero2")
                        .HasColumnType("real");

                    b.Property<float>("BZero4")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ArviPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.ArviPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ArviPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.ArviPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArviId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ArviPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.ArviSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ArviSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.ArviSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ArviSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.EviPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("BZero2")
                        .HasColumnType("real");

                    b.Property<float>("BZero4")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EviPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.EviPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EviPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.EviPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EviId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("EviPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.EviSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EviSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.EviSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EviSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.GndviPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BZero3")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GndviPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.GndviPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GndviPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.GndviPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GNdviId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GndviPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.GndviSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GndviSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.GndviSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GndviSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.MndwiPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("B11")
                        .HasColumnType("real");

                    b.Property<float>("BZero3")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MndwiPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.MndwiPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MndwiPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.MndwiPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MndWiId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MndwiPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.MndwiSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MndwiSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.MndwiSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("MndwiSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdmiPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("B11")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NdmiPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdmiPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NdmiPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdmiPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NdMiId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NdmiPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdmiSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NdmiSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdmiSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NdmiSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdviPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BZero4")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NdviPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdviPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NdviPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdviPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NdViId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("NdviPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdviSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NdviSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.NdviSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("NdviSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OrviPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BZero3")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OrviPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OrviPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OrviPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OrviPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrViId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OrviPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OrviSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("OrviSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OrviSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("OrviSharedReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OsaviPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BZero4")
                        .HasColumnType("real");

                    b.Property<float>("BZero8")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EPS")
                        .HasColumnType("real");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OsaviPoints");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OsaviPolygon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsColored")
                        .HasColumnType("boolean");

                    b.Property<Polygon>("Polygon")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid?>("PreviewImagePath")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductSourceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SatelliteProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OsaviPolygons");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OsaviPolygonRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OsaViId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OsaviPolygonRelations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OsaviSeasonReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("OsaviSeasonReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Indices.OsaviSharedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Average")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMax")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CropId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TotalMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalMin")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("OsaviSharedReports");
                });
#pragma warning restore 612, 618
        }
    }
}
