// <auto-generated />
using System;
using System.Collections.Generic;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.Sentinel
{
    [DbContext(typeof(MasofaSentinelDbContext))]
    [Migration("20260115130713_Fix_Migration")]
    partial class Fix_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel.Sentinel2ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OriginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SatellateProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SentinelInspireMetadataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SentinelL1CProductMetadataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SentinelL1CTileMetadataId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SentinelProductQualityMetadataId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreateAt")
                        .HasDatabaseName("idx_sentinel2_products_create_at");

                    b.HasIndex("SatellateProductId")
                        .HasDatabaseName("idx_sentinel2_products_satellite_id");

                    b.HasIndex("SentinelInspireMetadataId")
                        .HasDatabaseName("idx_sentinel2_products_inspire_id");

                    b.ToTable("Sentinel2Products");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel.SentinelInspireMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterSetCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EastBoundLongitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HierarchyLevelCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataStandardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetadataStandardVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NorthBoundLatitude")
                        .HasColumnType("numeric");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceSystemCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceSystemCodeSpace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SouthBoundLatitude")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("WestBoundLongitude")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DateStamp")
                        .HasDatabaseName("idx_sentinel_inspire_datestamp");

                    b.HasIndex("FileIdentifier")
                        .HasDatabaseName("idx_sentinel_inspire_file_identifier");

                    b.HasIndex("WestBoundLongitude", "EastBoundLongitude", "SouthBoundLatitude", "NorthBoundLatitude")
                        .HasDatabaseName("idx_sentinel_inspire_bbox");

                    b.ToTable("SentinelInspireMetadata");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel.SentinelL1CProductMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlueChannel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("DatatakeRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtPosList")
                        .HasColumnType("text");

                    b.Property<DateTime>("GenerationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeoTables")
                        .HasColumnType("text");

                    b.Property<string>("GippFilesRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GranulesRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GreenChannel")
                        .HasColumnType("integer");

                    b.Property<string>("HorizontalCsType")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("OffsetsRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PixelOrigin")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingBaseline")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingLevel")
                        .HasColumnType("text");

                    b.Property<string>("ProductDoi")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProductStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProductStopTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductType")
                        .HasColumnType("text");

                    b.Property<string>("ProductUri")
                        .HasColumnType("text");

                    b.Property<int>("QuantificationValue")
                        .HasColumnType("integer");

                    b.Property<string>("RasterCsType")
                        .HasColumnType("text");

                    b.Property<int>("RedChannel")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceBand")
                        .HasColumnType("integer");

                    b.Property<double>("ReflectanceU")
                        .HasColumnType("double precision");

                    b.Property<string>("SolarIrradianceListRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialValuesRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpectralBandIds")
                        .HasColumnType("text");

                    b.Property<string>("SpectralInformationListRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpectralPhysicalBands")
                        .HasColumnType("text");

                    b.Property<string>("SpectralResolutions")
                        .HasColumnType("text");

                    b.Property<string>("SpectralWavelengthCentrals")
                        .HasColumnType("text");

                    b.Property<string>("SpectralWavelengthMaxs")
                        .HasColumnType("text");

                    b.Property<string>("SpectralWavelengthMins")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GenerationTime")
                        .HasDatabaseName("idx_sentinel_l1c_product_metadata_generation_time");

                    b.HasIndex("ProductStartTime")
                        .HasDatabaseName("idx_sentinel_l1c_product_metadata_start_time");

                    b.HasIndex("ProductStopTime")
                        .HasDatabaseName("idx_sentinel_l1c_product_metadata_stop_time");

                    b.ToTable("SentinelL1CProductMetadata");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel.SentinelL1CTileMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchivingCentre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ArchivingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CloudyPixelPercentage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("DatastripId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DegradedDataPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("DownlinkPriority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GeopositionsRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorizontalCSCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorizontalCSName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("MeanSunAngleAzimuthAngle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeanSunAngleZenithAngle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MeanViewingIncidenceAngleListRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PixelLevelQIRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SensingTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SizesRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SnowPixelPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("SunAnglesAzimuthColStepValue")
                        .HasColumnType("double precision");

                    b.Property<double>("SunAnglesAzimuthRowStepValue")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("SunAnglesAzimuthValuesList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<double>("SunAnglesZenithColStepValue")
                        .HasColumnType("double precision");

                    b.Property<double>("SunAnglesZenithRowStepValue")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<string>>("SunAnglesZenithValuesList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViewingIncidenceAnglesGridsRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SentinelL1CTileMetadata");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel.SentinelProductQualityMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksRaw")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatorVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GippVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlobalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidityStart")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidityStop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SentinelProductQualityMetadata");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel2GenerateIndexStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ArviDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("ArviTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("EviDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("EviTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("GndviDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("GndviTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("MndwiDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("MndwiTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("NdmiDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("NdmiTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("NdviDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("NdviTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("NdwiDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("NdwiTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrviDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrviTiff")
                        .HasColumnType("boolean");

                    b.Property<bool>("OsaviDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("OsaviTiff")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Sentinel2ProductQueue")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Sentinel2GenerateIndexStatus");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel2ProductMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChecksumMd5")
                        .HasColumnType("text");

                    b.Property<DateTime>("ContentDateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ContentDateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EvictionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Footprint")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OriginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("S3Path")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContentDateEnd")
                        .HasDatabaseName("idx_sentinel2_product_metadata_content_date_end");

                    b.HasIndex("ContentDateStart")
                        .HasDatabaseName("idx_sentinel2_product_metadata_content_date_start");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_sentinel2_product_metadata_product_id");

                    b.HasIndex("ContentDateStart", "ContentDateEnd")
                        .HasDatabaseName("idx_sentinel2_product_metadata_content_dates");

                    b.ToTable("Sentinel2ProductsMetadata");
                });

            modelBuilder.Entity("Masofa.Common.Models.Satellite.Sentinel2ProductQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("OriginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QueueStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreateAt")
                        .HasDatabaseName("idx_sentinel2_product_queue_create_at");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("idx_sentinel2_product_queue_product_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_sentinel2_product_queue_status");

                    b.ToTable("Sentinel2ProductsQueue");
                });
#pragma warning restore 612, 618
        }
    }
}
