using Masofa.Depricated.DataAccess.DepricatedUdictServerTwo;
using MediatR;
using Microsoft.AspNetCore.Mvc.Formatters;
using System.Collections.Generic;
using System.Reflection;
using System.Text;

namespace Masofa.BusinessLogic.Cli.CodeGenerator
{
    public class CGetDbSetAddCodeGenCommand : IRequest
    {
        public string ResultPath { get; set; }
    }

    public class CGetDbSetAddCodeGenCommandHandler : IRequestHandler<CGetDbSetAddCodeGenCommand>
    {
        public async Task Handle(CGetDbSetAddCodeGenCommand request, CancellationToken cancellationToken)
        {
            try
            {
                var mappings = new List<(Type SourceClass, Type TargetClass)>();
                var types = typeof(Masofa.Depricated.DataAccess.DepricatedUdictServerTwo.Models.AdministrativeUnit).Assembly
                    .GetTypes()
                    .Where(m => m.GetCustomAttribute<Masofa.Depricated.DataAccess.DepricatedUdictServerTwo.MigrationCompareAttribute>() != null);

                foreach (var item in types)
                {
                    mappings.Add(new()
                    {
                        SourceClass = item,
                        TargetClass = item.GetCustomAttribute<MigrationCompareAttribute>().CompareToType
                    });
                }
                var sb = new StringBuilder();
                // Собираем все уникальные using'и
                var usings = new HashSet<string>();
                foreach (var (source, target) in mappings)
                {
                    if (!string.IsNullOrEmpty(source.Namespace)) usings.Add(source.Namespace);
                    if (!string.IsNullOrEmpty(target.Namespace)) usings.Add(target.Namespace);
                }

                var temp = new
                {
                    blabla = "blala",
                    ffff = "fooo"
                };

                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("// ⚠️ Этот файл сгенерирован автоматически. Не редактируй вручную.");
                sb.AppendLine();
                foreach (var ns in usings.OrderBy(x => x))
                {
                    sb.AppendLine($"using {ns};");
                }
                sb.AppendLine();
                sb.AppendLine("namespace Generated.Converters");
                sb.AppendLine("{");
                sb.AppendLine("     /// <summary>");
                sb.AppendLine("     /// Содержит implicit-операторы для преобразования моделей");
                sb.AppendLine("     /// </summary>");
                sb.AppendLine("     public static class DbSetAddInvoce");// для поддержки partial
                sb.AppendLine("     {");
                sb.AppendLine();

                foreach (var item in mappings)
                {
                    sb.AppendLine($"        public static void Add({item.TargetClass.Namespace}.{item.TargetClass.Name} source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)");
                    sb.AppendLine("         {");
                    sb.AppendLine("             if (source == null) return;");
                    sb.AppendLine($"            dbContext.Set<{item.TargetClass.Namespace}.{item.TargetClass.Name}>().Add(source);");
                    sb.AppendLine($"            dbContext.SaveChanges();");
                    sb.AppendLine("         }");
                }

                sb.AppendLine("     }");
                sb.AppendLine();
                sb.AppendLine("}");
                var classText = sb.ToString();

                var path = Path.Combine(request.ResultPath, $"DbSetAddInvoce_{DateTime.Now.ToString("yyyy_MM_dd_hh_mm")}.cs");
                File.WriteAllText(path, classText);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }
    }
}
