// <auto-generated />
using System;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.Ugm
{
    [DbContext(typeof(MasofaUgmDbContext))]
    [Migration("20251218082017_Add_AgroClimaticZone_Relation")]
    partial class Add_AgroClimaticZone_Relation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.Ugm.UgmWeatherData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AirTMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("AirTMin")
                        .HasColumnType("double precision");

                    b.Property<string>("CloudAmount")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayPart")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int?>("IsOccasional")
                        .HasColumnType("integer");

                    b.Property<int?>("IsPossible")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Precipitation")
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int?>("Thunderstorm")
                        .HasColumnType("integer");

                    b.Property<string>("TimePeriod")
                        .HasColumnType("text");

                    b.Property<string>("WeatherCode")
                        .HasColumnType("text");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<int?>("WindDirectionChange")
                        .HasColumnType("integer");

                    b.Property<int?>("WindSpeedMax")
                        .HasColumnType("integer");

                    b.Property<int?>("WindSpeedMaxAfterChange")
                        .HasColumnType("integer");

                    b.Property<int?>("WindSpeedMin")
                        .HasColumnType("integer");

                    b.Property<int?>("WindSpeedMinAfterChange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UgmWeatherData");
                });

            modelBuilder.Entity("Masofa.Common.Models.Ugm.UgmWeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgroclimaticZoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRegionalCenter")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("UgmRegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UgmWeatherStations");
                });
#pragma warning restore 612, 618
        }
    }
}
