//// <auto-generated />
//using System;
//using Masofa.DataAccess;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

//#nullable disable

//namespace Masofa.DataAccess.Migrations.WeatherReport
//{
//    [DbContext(typeof(MasofaWeatherReportDbContext))]
//    [Migration("20250922122614_Init_Database")]
//    partial class Init_Database
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.7")
//                .HasAnnotation("Relational:MaxIdentifierLength", 63);

//            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
//            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5DayWeatherForecast", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateOnly>("Date")
//                        .HasColumnType("date");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.HasKey("Id");

//                    b.ToTable("Era5DayWeatherForecasts");
//                });

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5DayWeatherReport", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateOnly>("Date")
//                        .HasColumnType("date");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.HasKey("Id");

//                    b.ToTable("Era5DayWeatherReports");
//                });

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5HourWeatherForecast", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateOnly>("Date")
//                        .HasColumnType("date");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<int>("Hour")
//                        .HasColumnType("integer");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.HasKey("Id");

//                    b.ToTable("Era5HourWeatherForecasts");
//                });

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5HourWeatherReport", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<DateOnly>("Date")
//                        .HasColumnType("date");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<int>("Hour")
//                        .HasColumnType("integer");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.HasKey("Id");

//                    b.ToTable("Era5HourWeatherReports");
//                });

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5MonthWeatherReport", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<int>("Month")
//                        .HasColumnType("integer");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.Property<int>("Year")
//                        .HasColumnType("integer");

//                    b.HasKey("Id");

//                    b.ToTable("Era5MonthWeatherReports");
//                });

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5WeekWeatherReport", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<DateOnly>("WeekEnd")
//                        .HasColumnType("date");

//                    b.Property<DateOnly>("WeekStart")
//                        .HasColumnType("date");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.HasKey("Id");

//                    b.ToTable("Era5WeekWeatherReports");
//                });

//            modelBuilder.Entity("Masofa.Common.Models.Era.Era5YearWeatherReport", b =>
//                {
//                    b.Property<Guid>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("uuid");

//                    b.Property<double>("Fallout")
//                        .HasColumnType("double precision");

//                    b.Property<double>("Humidity")
//                        .HasColumnType("double precision");

//                    b.Property<double>("SolarRadiationInfluence")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMax")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMaxTotal")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMin")
//                        .HasColumnType("double precision");

//                    b.Property<double>("TemperatureMinTotal")
//                        .HasColumnType("double precision");

//                    b.Property<Guid?>("WeatherStation")
//                        .HasColumnType("uuid");

//                    b.Property<double>("WindDerection")
//                        .HasColumnType("double precision");

//                    b.Property<double>("WindSpeed")
//                        .HasColumnType("double precision");

//                    b.Property<int>("Year")
//                        .HasColumnType("integer");

//                    b.HasKey("Id");

//                    b.ToTable("Era5YearWeatherReports");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
