

using Masofa.Common.Models.SystemCrical;
using Masofa.Depricated.DataAccess.DepricatedUdictServerTwo;
using NetTopologySuite.Index.HPRtree;
using System.Reflection;
using System.Text;

namespace Masofa.Cli.DevopsUtil.Commands.CodeGenerators
{
    [BaseCommand("Compare Implict CodeGenerator", "Генератор кода для создания implicit операторов преобразования")]
    public class CImplictCodeGenCommand : IBaseCommand
    {
        public void Dispose()
        {

        }

        public async Task Execute()
        {
            try
            {
                var mappings = new List<(Type SourceClass, Type TargetClass)>();
                var types = typeof(Masofa.Depricated.DataAccess.DepricatedUdictServerTwo.Models.AdministrativeUnit).Assembly
                    .GetTypes()
                    .Where(m => m.GetCustomAttribute<Masofa.Depricated.DataAccess.DepricatedUdictServerTwo.MigrationCompareAttribute>() != null);

                foreach (var item in types)
                {
                    mappings.Add(new()
                    {
                        SourceClass = item,
                        TargetClass = item.GetCustomAttribute<MigrationCompareAttribute>().CompareToType
                    });
                }
                var sb = new StringBuilder();
                // Собираем все уникальные using'и
                var usings = new HashSet<string>();
                foreach (var (source, target) in mappings)
                {
                    if (!string.IsNullOrEmpty(source.Namespace)) usings.Add(source.Namespace);
                    if (!string.IsNullOrEmpty(target.Namespace)) usings.Add(target.Namespace);
                }

                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("// ⚠️ Этот файл сгенерирован автоматически. Не редактируй вручную.");
                sb.AppendLine();
                foreach (var ns in usings.OrderBy(x => x))
                {
                    sb.AppendLine($"using {ns};");
                }
                sb.AppendLine();
                sb.AppendLine("namespace Generated.Converters");
                sb.AppendLine("{");
                sb.AppendLine("     /// <summary>");
                sb.AppendLine("     /// Содержит implicit-операторы для преобразования моделей");
                sb.AppendLine("     /// </summary>");
                sb.AppendLine("     public static class ImplicitConverters");// для поддержки partial
                sb.AppendLine("     {");
                sb.AppendLine();

                foreach (var item in mappings)
                {

                    sb.AppendLine($"        /// <summary>");
                    sb.AppendLine($"        /// Неявное преобразование {item.SourceClass.FullName} → {item.TargetClass.FullName}");
                    sb.AppendLine($"        /// </summary>");
                    sb.AppendLine($"        public static {item.TargetClass.Namespace}.{item.TargetClass.Name} Convert({item.SourceClass.Namespace}.{item.SourceClass.Name} source)");
                    sb.AppendLine("         {");
                    sb.AppendLine("             if (source == null) return null;");
                    sb.AppendLine($"            var target = new {item.TargetClass.Namespace}.{item.TargetClass.Name}();");
                    sb.AppendLine("");
                    sb.AppendLine("             // === ПРОВЕРЬ МАППИНГ ПОЛЕЙ ===");
                    foreach (var itemT in item.TargetClass.GetProperties())
                    {
                        if (item.SourceClass.GetProperty(itemT.Name) == null)
                        {
                            continue;
                        }
                        sb.AppendLine($"             target.{itemT.Name} = source.{itemT.Name};");
                    }
                    sb.AppendLine("");
                    sb.AppendLine("             return target;");
                    sb.AppendLine("         }");
                }

                sb.AppendLine("     }");
                sb.AppendLine();
                sb.AppendLine("}");
                var classText = sb.ToString();

                File.WriteAllText($"ImplicitConverters_{DateTime.Now.ToString("yyyy_MM_dd_hh_mm")}.cs", classText);
            }
            catch (Exception ex) 
            {
                Console.WriteLine(ex.ToString());
            }
        }

        public Task Execute(string[] args)
        {
            return Execute();
        }
    }
}
