// <auto-generated />
using System;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.IBMWeather
{
    [DbContext(typeof(MasofaIBMWeatherDbContext))]
    partial class MasofaIBMWeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IBMMeteoStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminDistrict")
                        .HasColumnType("text");

                    b.Property<string>("AdminDistrictCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("AgroclimaticZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("IataCode")
                        .HasColumnType("text");

                    b.Property<string>("IcaoCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("LocId")
                        .HasColumnType("text");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("PostalKey")
                        .HasColumnType("text");

                    b.Property<string>("PwsId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IBMMeteoStations");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IBMWeatherAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminDistrict")
                        .HasColumnType("text");

                    b.Property<string>("AdminDistrictCode")
                        .HasColumnType("text");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AreaTypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Certainty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertaintyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disclaimer")
                        .HasColumnType("text");

                    b.Property<int>("DisplayRank")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EffectiveTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EffectiveTimeLocalTimeZone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndTimeLocalTimeZone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTimeUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventTrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpireTimeLocalTimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireTimeUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HeadlineText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IBMMeteoStationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IanaTimeZone")
                        .HasColumnType("text");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssueTimeLocalTimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageTypeCode")
                        .HasColumnType("integer");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeAdminDistrict")
                        .HasColumnType("text");

                    b.Property<string>("OfficeAdminDistrictCode")
                        .HasColumnType("text");

                    b.Property<string>("OfficeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeCountryCode")
                        .HasColumnType("text");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OnsetTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OnsetTimeLocalTimeZone")
                        .HasColumnType("text");

                    b.Property<string>("Phenomena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessTimeUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeverityCode")
                        .HasColumnType("integer");

                    b.Property<string>("Significance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UrgencyCode")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherAlertCategory")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherAlertResponseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IBMWeatherAlerts");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IBMWeatherAlertFloodInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FloodCrestTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloodCrestTimeLocalTimeZone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FloodEndTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloodEndTimeLocalTimeZone")
                        .HasColumnType("text");

                    b.Property<string>("FloodImmediateCause")
                        .HasColumnType("text");

                    b.Property<string>("FloodImmediateCauseCode")
                        .HasColumnType("text");

                    b.Property<string>("FloodLocationId")
                        .HasColumnType("text");

                    b.Property<string>("FloodLocationName")
                        .HasColumnType("text");

                    b.Property<string>("FloodRecordStatus")
                        .HasColumnType("text");

                    b.Property<string>("FloodRecordStatusCode")
                        .HasColumnType("text");

                    b.Property<string>("FloodSeverity")
                        .HasColumnType("text");

                    b.Property<string>("FloodSeverityCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FloodStartTimeLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FloodStartTimeLocalTimeZone")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("WeatherAlertId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("IBMWeatherAlertFloodInfos");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IBMWeatherData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("text");

                    b.Property<string>("DayOrNight")
                        .HasColumnType("text");

                    b.Property<string>("GridpointId")
                        .HasColumnType("text");

                    b.Property<int?>("Humidity")
                        .HasColumnType("integer");

                    b.Property<Guid>("IBMMeteoStationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<int?>("PrecipChance")
                        .HasColumnType("integer");

                    b.Property<double?>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<double?>("Qpf")
                        .HasColumnType("double precision");

                    b.Property<double?>("QpfSnow")
                        .HasColumnType("double precision");

                    b.Property<int?>("RelativeHumidity")
                        .HasColumnType("integer");

                    b.Property<double?>("RequestedLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("RequestedLongitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("Temperature")
                        .HasColumnType("integer");

                    b.Property<int?>("TemperatureMax")
                        .HasColumnType("integer");

                    b.Property<int?>("TemperatureMin")
                        .HasColumnType("integer");

                    b.Property<int?>("UvIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WindDirection")
                        .HasColumnType("integer");

                    b.Property<int?>("WindSpeed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IBMWeatherData");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IbmDayNormalizedWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IbmDayNormalizedWeathers");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IbmDayWeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IbmDayWeatherForecasts");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IbmDayWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IbmDayWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IbmMonthWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IbmMonthWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IbmWeekWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IbmWeekWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.IBMWeather.IbmYearWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IbmYearWeatherReports");
                });
#pragma warning restore 612, 618
        }
    }
}
