// <auto-generated />
using System;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.AnaliticReport
{
    [DbContext(typeof(MasofaAnaliticReportDbContext))]
    [Migration("20251021172942_Add_Database_Season_Fields_1")]
    partial class Add_Database_Season_Fields_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.MasofaAnaliticReport.FarmerRecomendationReportModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("FertilizationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FileStorageItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("GrowthStagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndicesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IrrigationJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<string>("MonitoringJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoilJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WeatherJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FarmerRecomendationReports");
                });
#pragma warning restore 612, 618
        }
    }
}
