// <auto-generated />
using System;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.Weather
{
    [DbContext(typeof(MasofaWeatherDbContext))]
    [Migration("20250819121720_Update_Database")]
    partial class Update_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.Weather.AgroClimaticZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .HasColumnType("text");

                    b.Property<string>("NameUz")
                        .HasColumnType("text");

                    b.Property<string>("Polygon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("PolygonGeom")
                        .HasColumnType("geometry");

                    b.HasKey("Id");

                    b.ToTable("AgroClimaticZones");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.AgroClimaticZoneMonthNorm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgroClimaticZoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<int?>("M")
                        .HasColumnType("integer");

                    b.Property<double?>("PrecipitationAvgNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrecipitationMedNorm")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<double?>("SolarRadiationAvgNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarRadiationMedNorm")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("TemperatureAvgNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureMedNorm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AgroClimaticZoneMonthNorms");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.AgroClimaticZoneNorm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgroClimaticZoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<int?>("D")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<int?>("M")
                        .HasColumnType("integer");

                    b.Property<double?>("PrecipitationAvgNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrecipitationMedNorm")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<double?>("SolarRadiationAvgNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarRadiationMedNorm")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double?>("TemperatureAvgNorm")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureMedNorm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AgroClimaticZoneNorms");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.AgroClimaticZonesWeatherRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PrecRate")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempRate")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AgroClimaticZonesWeatherRates");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgroClimaticZonesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.ApplicationProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Application")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationPropertys");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobStatusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("ContentSize")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("JobStatus")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserInfo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("ColumnY")
                        .HasColumnType("integer");

                    b.Property<string>("Iso")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Mhobt")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Polygon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("PolygonGeom")
                        .HasColumnType("geometry");

                    b.Property<int?>("RegionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RegionNameEn")
                        .HasColumnType("text");

                    b.Property<string>("RegionNameRu")
                        .HasColumnType("text");

                    b.Property<string>("RegionNameUz")
                        .HasColumnType("text");

                    b.Property<int?>("RowX")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.RegionsAgroClimaticZone", b =>
                {
                    b.Property<Guid>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgroClimaticZonesId")
                        .HasColumnType("uuid");

                    b.HasKey("RegionId");

                    b.ToTable("RegionsAgroClimaticZones");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.RegionsDump", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Active")
                        .HasColumnType("boolean");

                    b.Property<int?>("ColumnY")
                        .HasColumnType("integer");

                    b.Property<string>("Iso")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Mhobt")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Polygon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("PolygonGeom")
                        .HasColumnType("geometry");

                    b.Property<int?>("RegionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("RegionName")
                        .HasColumnType("text");

                    b.Property<int?>("RowX")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RegionsDumps");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.RegionsWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("PrecDev")
                        .HasColumnType("double precision");

                    b.Property<double?>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Temp")
                        .HasColumnType("double precision");

                    b.Property<double?>("TempDev")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RegionsWeathers");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReportType")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceQuery")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.WeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("X")
                        .HasColumnType("integer");

                    b.Property<int?>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherStations");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.WeatherStationAgroClimaticZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgroClimaticZonesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeatherStationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WeatherStationAgroClimaticZones");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.WeatherStationsDataEx", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("HumiditySoil2m")
                        .HasColumnType("double precision");

                    b.Property<double?>("HumiditySoil50cm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temp1030cm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temp10cmUnder")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temp30100cm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature1mAbove")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature2mUnder")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureGroundLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureSoil")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WeatherStationsDataEx");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.WeatherStationsDatum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CloudCover")
                        .HasColumnType("double precision");

                    b.Property<int?>("ConditionCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DewPoint")
                        .HasColumnType("double precision");

                    b.Property<double?>("HumidityMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("HumidityMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<double?>("RelativeHumidity")
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarRadiation")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeedMin")
                        .HasColumnType("double precision");

                    b.Property<double?>("Windchill")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WeatherStationsDatum");
                });

            modelBuilder.Entity("Masofa.Common.Models.Weather.XslsUzUnputColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DbColumnName")
                        .HasColumnType("text");

                    b.Property<string>("DbTableName")
                        .HasColumnType("text");

                    b.Property<string>("XlsColumnName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("XslsUzUnputColumns");
                });
#pragma warning restore 612, 618
        }
    }
}
