// <auto-generated />
// ⚠️ Этот файл сгенерирован автоматически. Не редактируй вручную.

using Masofa.Common.Models.Dictionaries;
using Masofa.Depricated.DataAccess.DepricatedUdictServerTwo.Models;

namespace Masofa.Cli.DevopsUtil.Commands.Migration
{
     /// <summary>
     /// Содержит implicit-операторы для преобразования моделей
     /// </summary>
     public static class DbSetAddInvoce
     {
        public static void Add(Masofa.Common.Models.Dictionaries.AdministrativeUnit source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.AdministrativeUnit>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.AgroclimaticZone source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.AgroclimaticZone>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.AgroMachineType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.AgroMachineType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.AgroOperation source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.AgroOperation>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.AgrotechnicalMeasure source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.AgrotechnicalMeasure>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.AgroTerm source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.AgroTerm>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.BidContent source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.BidContent>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.BidState source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.BidState>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.BidType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.BidType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.BusinessType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.BusinessType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.ClimaticStandard source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.ClimaticStandard>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Crop source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Crop>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.CropPeriod source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.CropPeriod>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.CropPeriodVegetationIndex source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.CropPeriodVegetationIndex>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.DicitonaryType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.DicitonaryType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Disease source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Disease>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.EntomophageType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.EntomophageType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.ExperimentalFarmingMethod source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.ExperimentalFarmingMethod>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Fertilizer source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Fertilizer>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.FertilizerType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.FertilizerType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.FieldUsageStatus source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.FieldUsageStatus>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Firm source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Firm>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.FlightTarget source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.FlightTarget>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.IrrigationMethod source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.IrrigationMethod>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.IrrigationSource source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.IrrigationSource>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.MeasurementUnit source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.MeasurementUnit>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.MeliorativeMeasureType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.MeliorativeMeasureType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Person source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Person>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.PestType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.PestType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.PesticideType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.PesticideType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Pesticide source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
             dbContext.Set<Masofa.Common.Models.Dictionaries.Pesticide>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.ProductQualityStandard source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.ProductQualityStandard>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.ProviderWeatherCondition source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.ProviderWeatherCondition>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Region source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Region>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.RegionMap source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.RegionMap>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.RegionType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.RegionType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.SoilType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.SoilType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.SolarRadiationInfluence source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.SolarRadiationInfluence>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.SystemDataSource source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.SystemDataSource>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.TaskStatus source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.TaskStatus>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.UavCameraType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.UavCameraType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.UavDataType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.UavDataType>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.Variety source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.Variety>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.VarietyFeature source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.VarietyFeature>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.VegetationIndex source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.VegetationIndex>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.VegetationPeriod source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.VegetationPeriod>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.WaterResource source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.WaterResource>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.WeatherStation source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.WeatherStation>().Add(source);
             dbContext.SaveChanges();
         }
        public static void Add(Masofa.Common.Models.Dictionaries.WeatherStationType source, Masofa.DataAccess.MasofaDictionariesDbContext dbContext)
         {
             if (source == null) return;
            dbContext.Set<Masofa.Common.Models.Dictionaries.WeatherStationType>().Add(source);
             dbContext.SaveChanges();
         }
     }

}
