// <auto-generated />
using System;
using Masofa.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Masofa.DataAccess.Migrations.Era
{
    [DbContext(typeof(MasofaEraDbContext))]
    [Migration("20251024121027_Update_Database_IsPublic")]
    partial class Update_Database_IsPublic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Masofa.Common.Models.Era.Era5DayNormalizedWeather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<double>("SolarRadiationInfluence")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Era5DayNormalizedWeather");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.Era5DayWeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("SolarRadiationInfluence")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Era5DayWeatherForecasts");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.Era5DayWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsFrostDanger")
                        .HasColumnType("boolean");

                    b.Property<double>("SolarRadiationInfluence")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Era5DayWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.Era5MonthWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<double>("SolarRadiationInfluence")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Era5MonthWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.Era5WeekWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("SolarRadiationInfluence")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("WeekEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Era5WeekWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.Era5YearWeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Fallout")
                        .HasColumnType("double precision");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double>("SolarRadiationInfluence")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMaxTotal")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureMinTotal")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("WeatherStation")
                        .HasColumnType("uuid");

                    b.Property<double>("WindDerection")
                        .HasColumnType("double precision");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Era5YearWeatherReports");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.EraWeatherData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CloudCover")
                        .HasColumnType("double precision");

                    b.Property<int?>("ConditionIds")
                        .HasColumnType("integer");

                    b.Property<double?>("DewPoint")
                        .HasColumnType("double precision");

                    b.Property<Guid>("EraWeatherStationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("GroundTemperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("OriginalDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Precipitation")
                        .HasColumnType("double precision");

                    b.Property<double?>("RelativeHumidity")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilHumidity2m")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilHumidity50cm")
                        .HasColumnType("double precision");

                    b.Property<double?>("SoilTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("SolarRadiation")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("double precision");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EraWeatherData");
                });

            modelBuilder.Entity("Masofa.Common.Models.Era.EraWeatherStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreateUser")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastUpdateUser")
                        .HasColumnType("uuid");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EraWeatherStations");
                });
#pragma warning restore 612, 618
        }
    }
}
